build:
    environment:
        python: 3.8.9
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [py-scrutinizer-run]

checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - 'tests/*'
