sudo: false
language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
before_install:
 - pip install --upgrade pip
 - pip install -U setuptools
install:
  - pip install -r requirements-dev.txt
  - python setup.py develop
script:
 - py.test --cov atramhasis --cov-report term-missing tests
after_success:
 - coveralls
