language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
install:
 - easy_install -U setuptools
 - python setup.py -q install
 - pip install -U pytest pytest-cov coveralls webtest
script:
  py.test --cov atramhasis --cov-report term-missing atramhasis/tests
after_success:
  coveralls