language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
install:
 - pip install -U setuptools
 - pip install -r requirements.txt
 - pip install -U pytest pytest-cov coveralls webtest
# - python setup.py -q install
script:
  py.test --cov atramhasis --cov-report term-missing tests
after_success:
  coveralls
